targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - $package$
    builders:
      artemis:
        options:
          scalar_mapping:
            - custom_parser_import: 'package:dashtech/infrastructure/core/graphql/type_coercers.dart'
              graphql_type: DateTime
              dart_type: DateTime
          schema_mapping:
            - schema: 'schema.graphql'
              queries_glob: 'lib/infrastructure/**.graphql'
              output: 'lib/infrastructure/core/graphql/graphql_api.dart'
