# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build .ipa and push a new beta build to TestFlight"
  lane :beta_deploy do
    build_app(
        workspace: "Runner.xcworkspace", scheme: "Runner",
        export_method: "app-store",
        include_symbols: true,
        export_options: {
            provisioningProfiles: {
                ENV['APP_IDENTIFIER'] => ENV['PROVISIONING_PROFILE_NAME']
            }
        }
    )
    upload_to_testflight
    #upload_dsyms
    clean_build_artifacts
  end

  desc "Just push a new beta build to TestFlight"
  lane :call_upload_to_testflight do
    upload_to_testflight
  end

  desc "Refresh DSYMs files from iTunes Connect and upload symbols to Crashlytics"
  lane :upload_dsyms do
    upload_symbols_to_crashlytics(gsp_path: "./Runner/GoogleService-Info.plist")
  end
end
