/// Flutter icons Cajole
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cajole
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const String _kFontFam = 'CustomIcons';

  static const IconData search = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
  static const IconData pwd = IconData(
    0xe804,
    fontFamily: _kFontFam,
  );
  static const IconData facebook = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
  static const IconData google = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData linkedin = IconData(
    0xe807,
    fontFamily: _kFontFam,
  );
  static const IconData gilft = IconData(
    0xe808,
    fontFamily: _kFontFam,
  );
  static const IconData user = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
  static const IconData info = IconData(
    0xe80a,
    fontFamily: _kFontFam,
  );
  static const IconData picture = IconData(
    0xe80b,
    fontFamily: _kFontFam,
  );
  static const IconData attached = IconData(
    0xe80c,
    fontFamily: _kFontFam,
  );
  static const IconData check = IconData(
    0xe80d,
    fontFamily: _kFontFam,
  );
  static const IconData o = IconData(
    0xe80e,
    fontFamily: _kFontFam,
  );
  static const IconData trac__127 = IconData(
    0xe80f,
    fontFamily: _kFontFam,
  );
}
